config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :publications do
    resources :comments, only: [:create]
  end
  devise_for :users
  post '/reactions', to: 'reactions#user_reaction', as: 'user_reaction'
  get '/my_reactions', to: 'reactions#publication_with_reactions', as: 'my_reactions'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "publications#index"
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  has_many :reactions, dependent: :destroy
  has_many :users, through: :reactions
  has_many :comments, dependent: :destroy

  def count_with_kind(arg)
      number = self.reactions.where(kind: arg).count
      return "#{arg} - #{number}"
  end
  def find_kind_user_relation(user)
      self.reactions.find_by(user_id: user.id).kind
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit update destroy ]

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
    @publication = Publication.new
    
  end

  # GET /publications/1 or /publications/1.json
  def show
    @publication = Publication.find(params[:id])
    @comments = @publication.comments
    @comment = Comment.new
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.user_id = current_user.id

    @comment = Comment.new
    @comment.user = current_user

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:tittle, :image, :content)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication, class: "my-form") do |form| %>
  <% if publication.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Título, class: "form-label" %>
    <%= form.text_field :tittle, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Imagen, class: "form-label" %>
    <%= form.text_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Contenido, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.submit "Guardar", class: "btn btn-dark mt-3"  %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <div id="<%= dom_id publication %>">
      <div class="card mb-3 custom-card">
        <img src="<%= publication.image %>" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= publication.tittle %></h5>
          <p class="card-text"><%= publication.content %></p>
          <p class="card-text"><small class="text-body-secondary"><%= publication.user.email %></small></p>
          <%= render "reactions/counters" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Show this publication", @publication %> |
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/index.html.erb
<h1 class=>Publicaciones</h1>

<hr> 

<div id="publications">
  <% @publications.each do |publication| %>
    <%= render publication %>
    <p>
      <%= link_to "Ver comentarios", publication, class:"btn btn-dark mt-3" %>
    </p>
    <hr> 
  <% end %>
</div>


<%= link_to "Publicar", new_publication_path, class:"btn btn-dark mt-3" %>

app/views/publications/new.html.erb
<h1>Nueva publicación</h1>

<%= render "form", publication: @publication %>

<br>
<hr>

<div>
  <%= link_to "Volver", publications_path, class:"btn btn-dark mt-3" %>
</div>

app/views/publications/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= render "reactions/options" %>
    </div>
  </div>
</div>

<hr>

<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <%= render @publication %>
      <div class="actions">
        <% if user_signed_in? %>
          <% if current_user.id == @publication.user_id %>
            <div class="d-inline-block">
              <%= link_to "Editar publicación", edit_publication_path(@publication), class: "btn btn-secondary mr-2" %>
            </div>
            <div class="d-inline-block">
              <%= button_to "Eliminar", @publication, method: :delete, class: "btn btn-secondary mr-2", data: { confirm: "¿Estás seguro de que deseas eliminar esta publicación?" } %>
            </div>
          <% end %>
        <% end %>
        <%= link_to "Regresar a las publicaciones", publications_path, class: "btn btn-secondary mr-2 " %>
      </div>
    </div>
  </div>
</div><br/>

<hr>

<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h3>Comentarios:</h3>

      <% if @comments.present? %>
        <% @comments.each do |comment| %>
          <div class="card comment-card mb-2">
            <div class="card-body">
              <p><%= comment.user.email %></p>
              <%= comment.content %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <div class="comment-form">
        <%= form_with(model: [@publication, Comment.new]) do |form| %>
          <div class="form-group">
            <%= form.text_area :content, class: "form-control" %>
          </div>

          <div class="actions">
            <%= form.submit "Agregar un comentario", class:"btn btn-secondary mt-3" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>