config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :publications do
    resources :comments, only: [:create]
  end
  devise_for :users
  post '/reactions', to: 'reactions#user_reaction', as: 'user_reaction'
  get '/my_reactions', to: 'reactions#publication_with_reactions', as: 'my_reactions'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "publications#index"
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
    before_action :authenticate_user!
    
        def user_reaction
            @user = current_user
            @publication = Publication.find(params[:publication_id])
            reaction = Reaction.find_by(user_id: @user.id, publication_id: @publication.id)
            if reaction
                return flash.now[:alert] = 'Ya has reaccionado a esta publicación'
            else
                @new_reaction = Reaction.new(user_id: @user.id, publication_id: @publication.id, kind: params[:kind])
                respond_to do |format|
                    if @new_reaction.save!
                    format.html { redirect_to publication_path(@publication), notice: "#{current_user.email} le ha puesto #{@new_reaction.kind}
                    a la publicación" }
                    else
                    format.html { redirect_to publication_path(@publication), status: :unprocessable_entity }
                    end
                end
            end
        end
        def publication_with_reactions
            @reactions = current_user.reactions
            publication_ids = @reactions.map(&:publication_id)
            @publication = Publication.where(id: publication_ids)
        end
    end
    

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/reactions/_counters.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <ul class="list-inline">
        <% Reaction.kinds.each do |kind| %>
          <li class="list-inline-item">
            <span class="badge badge-secondary">
              <span class="text-dark" style="color: white;">
                <% reaccion = case kind
                  when 'like' 
                    'Me gusta'
                  when 'dislike'
                    'No me gusta'
                  when 'funny'
                    'Gracioso'
                  when 'angry'
                    'Me enoja'
                  else
                    kind
                end %>
                <%= @publication.reactions.where(kind: kind).count %> <%= reaccion %>
              </span>
            </span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/reactions/_options.html.erb
<div class="container">
  <div class="btn-group d-flex" role="group">
    <% Reaction.kinds.each do |kind| %>
      <% reaction_text = case kind
        when "like"
          "Me gusta"
        when "dislike"
          "No me gusta"
        when "funny"
          "Gracioso"
        when "angry"
          "Me enoja"
        else
          kind
        end
      %>
      <%= button_to reaction_text, user_reaction_path(publication_id: @publication.id, kind: kind), method: :post, class: "btn btn-primary my-1 mx-1 btn-sm" %>
    <% end %>
  </div>
</div>  

app/views/reactions/publication_with_reactions.html.erb
<h1>Tus reacciones</h1>

<ul>
  <% @publication.each do |publication| %>
    <li class="card p-3 mb-3">
      <%= content_tag :strong, publication.user.email %>
      <%= publication.tittle %> -
      <%= publication.reactions.find_by(user_id: current_user.id).kind %>
      <%= link_to "Ir", publication, class: "btn btn-dark mt-3" %>
    </li>
  <% end %>
</ul>